name: Main CI/CD Workflow
description: A CI/CD workflow that lints, builds, tests, and deploys code using a reusable workflow.
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - QA
          - PROD
      version:
        description: 'Optionally specify the version tag (e.g., v1.0.2)'
        required: false
        default: 'v1.0.0'
jobs:
  ci:
    strategy:
      matrix:
        node-version:  [16, 18]
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.operating-system }}
    if: ${{ github.ref_name == 'main' }}
    steps:
      - name: Run Reusable CI Workflow
        uses: ./.github/workflows/reusable-ci.yml
        with:
          node-version: ${{ matrix.node-version }}
          operating-system: ${{ matrix.operating-system }}
  DEV_Deploy:
    needs: ci
    strategy:
      matrix:
        node-version: [16, 18]
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.operating-system }}
    environment: DEV
    if: ${{ github.event.inputs.environment == 'DEV' }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: website-build-${{ matrix.operating-system }}-${{ matrix.node-version }}
      - name: listing out artifacts
        run: ls
      - name: Deploy to DEV environment
        run: |
          echo "Deploying version ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }} environment..." 
  QA_Deploy:
    needs: ci
    strategy:
      matrix:
        node-version: [16, 18]
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.operating-system }}
    environment: QA
    if: ${{ github.event.inputs.environment == 'QA' }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: website-build
      - name: listing out artifacts
        run: ls
      - name: Deploy to QA environment
        run: echo "Deploying ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }} environment..." 
  PROD_Deploy:
    needs: ci  
    strategy:
      matrix:
        node-version: [16, 18]
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.operating-system }}
    environment: PROD
    if: ${{ github.event.inputs.environment == 'PROD' }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: website-build
      - name: listing out artifacts
        run: ls
      - name: Deploy to PROD environment
        run: echo "Deploying ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }} environment..."

          