name: Trigger workflow only when files under src/** are modified
description: Trigger workflow only when files under src/** are modified
on:
  push:
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - QA
          - PROD
      version:
        description: 'Optionally specify the version tag (e.g., v1.0.2)'
        required: false
        default: 'v1.0.0'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Node Js setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm ci
      - name: Run Linting
        run: |
          npm run lint
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Node Js setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: | 
          npm ci
          npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: website-build
          path: dist
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Node Js setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
  DEV_Deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: DEV
    if: ${{ github.event.inputs.environment == 'DEV' }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: website-build
      - name: listing out artifacts
        run: ls
      - name: Deploy to DEV environment
        run: |
          echo "Deploying version ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }} environment..." 
  QA_Deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: QA
    if: ${{ github.event.inputs.environment == 'QA' }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: website-build
      - name: listing out artifacts
        run: ls
      - name: Deploy to QA environment
        run: echo "Deploying ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }} environment..." 
  PROD_Deploy:
    needs: build  
    runs-on: ubuntu-latest
    environment: PROD
    if: ${{ github.event.inputs.environment == 'PROD' }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: website-build
      - name: listing out artifacts
        run: ls
      - name: Deploy to PROD environment
        run: echo "Deploying ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }} environment..."

          