name: PR Trigger & Context variable Workflow
description: Trigger workflow on pull request to main and print branch + author
on:
  pull_request:
    branches:
      - main
      - 'feature/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Node Js setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm ci
      - name: Run Linting
        run: |
          npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Node Js setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: | 
          npm ci
          npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: website-build
          path: dist
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Node Js setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: website-build
      - name: listing out artifacts
        run: ls 
  pr-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR Context
        run: |
          echo "Pull Request opened from Branch:  ${{ github.head_ref }}"
          echo "Pull Request opened by Author: ${{ github.actor }}"

          