name: Conditional steps in feature branch
description: Run step only if branch == `main`
on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - QA
          - PROD
      version:
        description: 'Optionally specify the version tag (e.g., v1.0.2)'
        required: false
        default: 'v1.0.0'
jobs:
  lint:
    strategy:
      matrix:
        node-version: [14, 16, 18]
        operating-system: [ubuntu-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Node Js setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Run Linting
        run: |
          npm run lint
  build:
    strategy:
      matrix:
        node-version: [14, 16, 18]
        operating-system: [ubuntu-latest]
    needs: [lint, test]
    runs-on: ${{ matrix.operating-system }}
    if: ${{ github.ref_name == 'main'}}
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Node Js setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: | 
          npm ci
          npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: website-build-${{ matrix.node-version }}
          path: dist
  test:
    strategy:
      matrix:
        node-version: [14, 16, 18]
        operating-system: [ubuntu-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Node Js setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
  DEV_Deploy:
    needs: build
    strategy:
      matrix:
        node-version: [14, 16, 18]
        operating-system: [ubuntu-latest]
    runs-on: ${{ matrix.operating-system }}
    environment: DEV
    if: ${{ github.event.inputs.environment == 'DEV' }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: website-build-${{ matrix.node-version }}
      - name: listing out artifacts
        run: ls
      - name: Deploy to DEV environment
        run: |
          echo "Deploying version ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }} environment..." 
  QA_Deploy:
    needs: build
    strategy:
      matrix:
        node-version: [14, 16, 18]
        operating-system: [ubuntu-latest]
    runs-on: ${{ matrix.operating-system }}
    environment: QA
    if: ${{ github.event.inputs.environment == 'QA' }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: website-build
      - name: listing out artifacts
        run: ls
      - name: Deploy to QA environment
        run: echo "Deploying ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }} environment..." 
  PROD_Deploy:
    needs: build  
    strategy:
      matrix:
        node-version: [14, 16, 18]
        operating-system: [ubuntu-latest]
    runs-on: ${{ matrix.operating-system }}
    environment: PROD
    if: ${{ github.event.inputs.environment == 'PROD' }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: website-build
      - name: listing out artifacts
        run: ls
      - name: Deploy to PROD environment
        run: echo "Deploying ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }} environment..."

          