name: A basic workflow
description: Create a basic workflow to print 'Hello from GitHub Actions!' on push to main
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Node Js setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: | 
          npm ci
          vite build
          echo 'Hello from GitHub Actions!'
        
          