name: integrating composite action workflow
description: A workflow to lint, build, test, and deploy code using a custom composite action.
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - QA
          - PROD
      version:
        description: 'Optionally specify the version tag (e.g., v1.0.2)'
        required: false
        default: 'v1.0.0'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm ci
      - name: Run Linting
        run: npm run lint
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: List .github/actions contents
        run: ls -R ./.github/actions
      - name: Node Build Action
        uses: ./.github/actions/node-build
        with:
          node-version: '18'
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: website-build
          path: dist
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
  DEV_Deploy:
    needs: build
    # strategy:
    #   matrix:
    #     node-version: [16, 18]
    #     operating-system: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ubuntu-latest
    environment: DEV
    if: ${{ github.event.inputs.environment == 'DEV' }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: website-build
      - name: listing out artifacts
        run: ls
      - name: Deploy to DEV environment
        run: |
          echo "Deploying version ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }} environment..." 
  QA_Deploy:
    needs: build
    # strategy:
    #   matrix:
    #     node-version: [16, 18]
    #     operating-system: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ubuntu-latest
    environment: QA
    if: ${{ github.event.inputs.environment == 'QA' }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: website-build
      - name: listing out artifacts
        run: ls
      - name: Deploy to QA environment
        run: echo "Deploying ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }} environment..." 
  PROD_Deploy:
    needs: build  
    # strategy:
    #   matrix:
    #     node-version: [16, 18]
    #     operating-system: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ubuntu-latest
    environment: PROD
    if: ${{ github.event.inputs.environment == 'PROD' }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: website-build
      - name: listing out artifacts
        run: ls
      - name: Deploy to PROD environment
        run: echo "Deploying ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }} environment..."
